### ISSUE TITLE
Confusion matrix not plotting correclty

### ISSUE THREAD

**Issue by davesteps** [iterative/studio-support#22]
I have a plots csv file which creates a confusion matrix. It plots correctly when I use `dvc plots show ./confmat.csv` locally. My dvc yaml looks like: 

```
    plots:
    - ./confmat.csv:
        cache: false
        template: confusion
        x: actual
        y: predicted
```
However, it does not plot correctly in dvc studio, all I get is an empty plot:
![image](https://user-images.githubusercontent.com/5738970/124725919-d153ff80-defc-11eb-9d99-f8be5c830e73.png)

Thanks.
