### ISSUE TITLE
DVC Studio 'Run new experiment' fields

### ISSUE THREAD

**Issue by janchk** [iterative/studio-support#36]
It would be nice to have support for multiline text field for experiment configuration.
For example if I need to pass several elements to config in a list, I must write them in one tiny line which is not very convenient.
Here's an example:
```yaml
  callbacks:
    - callback: 'TensorBoard'
      args:
        log_dir: '../logs'
    - callback: 'ModelCheckpoint'
      args:
        filepath: 'data/checkpoints/ckpt_{epoch:03d}'
        save_best_only: True
        monitor: 'val_output_1_map'
```
which get  transformed in something like this 
![image](https://user-images.githubusercontent.com/9109987/136972510-77760d1d-5fd4-4c44-90b5-1986c5a199b1.png)
