### ISSUE TITLE
Multi remote feature

### ISSUE THREAD

**Issue by courentin** [iterative/studio-support#50]
Hello, we have a dvc repository with 2 remotes and intentionally no default remote. We need that because we have a data residency constraint by region.

Would it be possible to specify multiple data remote by projects?

**Comment by shcheklein** [comment]
@courentin qq - do you specify remote names in each `.dvc` file / `dvc.yaml` stage outputs?

**Comment by courentin** [comment]
Yes I do

**Comment by courentin** [comment]
Hello, do you have any news on this features? Is there a chance that it gets prioritized or do you have a workaround? :)

Thank you!

**Comment by shcheklein** [comment]
@courentin no updates yet.

Question. It's the same repo, but do you use separate remotes for different projects within that repository or it's within one repo, within one pipeline you have multiple remotes?

**Comment by courentin** [comment]
It's one pipeline with multiple remotes.

Basically we have the same pipeline that runs twice thanks to the foreach feature, and each run has a different remote.

Something like:
```
stages:
  train:
    foreach: languages
    do:
      cmd: python ..
      outs:
       - my_out:
         remote: ${key}
```
