### ISSUE TITLE
Plots in studio are not correct and missing data

### ISSUE THREAD

**Issue by haimat** [iterative/studio-support#72]
I am using DVCLive in our project and have the following DVC configuration for our plots in `dvc.yaml`:

```yaml
plots:
  - mAP:
      x: step
      y:
        dvclive/plots/metrics/map95.tsv: map95
        dvclive/plots/metrics/map50.tsv: map50
      title: Model Performance
      x_label: epoch
      y_label: value
  - PR:
      x: step
      y:
        dvclive/plots/metrics/precision.tsv: precision
        dvclive/plots/metrics/recall.tsv: recall
      title: Prevision vs. Recall
      x_label: epoch
      y_label: value
```

This produces the following plots via `dvc plots show`:
![image](https://user-images.githubusercontent.com/6633976/219689193-beda4b2e-9e25-4a50-9fef-c3c849b353dc.png)

However, the same data leads to these plots in Studio:
![image](https://user-images.githubusercontent.com/6633976/219689381-baedbc5e-ef3f-4c15-b563-d5e8380aaef3.png)

How can I get to the same plots in Studio as we get locally via `dvc`?
