### ISSUE TITLE
Missing parent commit (bnraches) for DVC experiments

### ISSUE THREAD

**Issue by leduckhc** [iterative/studio-support#92]
Hi,

I use gitlab CI run my experiments. So I am sure that the "parent" commit (branch) from which I run the dvc experiments. However, I do not see the the parent commit nor the branch. Here's the gitlab CI job that it runs. It goes something like in this like

```yaml
launch cml-runner:
  stage: launch
  image: iterativeai/cml:0-dvc3-base1
  variables:
    MACHINE_TYPE: m+v100
    MACHINE_LABELS: "cml-runner-gpu"
  script:
    # Reusability: Don't launch a new runner if an existing one has the same name or overlapping labels. If an existing matching (same name or overlapping labels) instance is busy, it'll still be reused.
    # This allows you to login to the instance using your public gitlab SSH key. The script is base64 encoded.
    - BASE64_SCRIPT=$(echo 'curl https://gitlab.com/${GITLAB_USER_LOGIN}.keys >> /home/ubuntu/.ssh/authorized_keys' | base64 -w 0)
    - cml runner launch
      --cloud=azure
      --cloud-region=eu-north
      --cloud-type="${MACHINE_TYPE}"
      --cloud-hdd-size=64
      --cloud-startup-script="${BASE64_SCRIPT}"
      --cloud-spot
      --reuse
      --labels="${MACHINE_LABELS}"

run cml-runner:
  stage: run
  tags: ["cml-runner-gpu"]
  image: $CI_REGISTRY_IMAGE/research-gpu:latest # this image is based on iterativeai/cml:0-dvc3-base1
  variables:
    PRJ_DIR: projects/XXX
  before_script:
    # without this line, it does not work
    - cml ci --fetch-depth=0
    - python -V
    - nvidia-smi
    - python -c "import torch; print('CUDA is available for torch:', torch.cuda.is_available())"
  script:
    - cd $PRJ_DIR
    - dvc config --global studio.token $DVC_STUDIO_TOKEN
    - dvc pull --allow-missing
    - dvc exp run
    - dvc exp push origin
```

(Maybe this might help. My branch name is in the form "projects/XXX")
